title: Kush Bhagat
email: kushbhagat0@gmail.com
description: Software engineer interested in distributed systems, useful applications, and machine learning.
baseurl: ""
url: "https://kushbhag.at"
github_username: kushb007
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - kushb007.github.io
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
